### ISSUE TITLE
warning in Xcode

### ISSUE THREAD

**Issue by geogerar** [nimati/FCAlertView#10]
Hi again,
I got the last commit of your tool and the issue with the index now is working ok!
Thanks a lot.
But now I get the following  warning in Xcode
"/Users/GEOGERAR/Documents/GEOGER IOS7 Apps/ZTEST/TEST/FCAlertView/FCAlertView.h:39:29: Pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified)"
in FCAlertView.h at delegate 
// Delegate
@property (nonatomic, weak) id<FCAlertViewDelegate> delegate;

can you take a look please?

George

**Comment by nimati** [comment]
Hi George,

That's great. Yeah that was a mistake on my end, sorry about that, I've released V1.0.6 which fixes this issue.

Cheers!
