### ISSUE TITLE
[!] Unable to find a specification for `FCAlertView`

### ISSUE THREAD

**Issue by chetansrm** [nimati/FCAlertView#12]
When do I install pod it gives this error showing in title

**Comment by nimati** [comment]
Hi @chetansrm,

Can you give me more info and also paste in the code you're using so I can look into it?

**Comment by chetansrm** [comment]
@nimati  I have resolved the problem.Problem was from my end.
  Thanx for attention

**Comment by nimati** [comment]
Oh ok, no worries! Let me know if you have any other questions.

Enjoy!
