### ISSUE TITLE
Example for Swift 

### ISSUE THREAD

**Issue by Danielthenew** [nimati/FCAlertView#13]
First of all nice Example very cool and much detail functions. 

Give it this example only in Objective-C or also in Swift?

**Comment by nimati** [comment]
Hi @Danielthenew,

Thank you! Swift is coming soon! Stay updated with the project and I'll notify you when swift is available.

Cheers!

**Comment by neegbeah** [comment]
You can use the bridging header and use it. You need to convert it to Swift if your not familiar with Objective-C. But heres an example:

`var alert = FCAlertView()`
`alert.showAlertInView(self, withTitle: "Alert Title", withSubtitle: "This is your alert's subtitle. Keep it short and concise. ", withCustomImage: nil, withDoneButtonTitle: nil, andButtons: nil);`

**Comment by nimati** [comment]
Interesting, I'll take a look! Thanks for sharing 😀

**Comment by Danielthenew** [comment]
Oke Thanks I am looking forward :) 
Yeah with header it must function but it´s better when all in swift.

**Comment by pjebs** [comment]
I don't think we need a example project in Swift given how easy it is to use in a swift project (I use it in swift project). The more important question is why wasn't the component itself written in Swift lol

**Comment by nimati** [comment]
@pjebs you have a point. It wasn't written in Swift simply because I have more experience with Objective-C. However, @k9101 is actually writing the swift version at the moment, so as soon as that's ready, should be good to go!

**Comment by krispenney** [comment]
Hey everyone! 

Everything should be about ready to go, just doing finishing off some testing now but feel free to give it try and let me know if you have any suggestions! I tried to make the API similar while also taking advantage of some Swift features (checkout the README). I included my (very basic) example project  if anyone want to check that out (I may port @nimati example to Swift if anyone wants it).

**Comment by nimati** [comment]
Perfect, thanks for the update Kris! @k9101 
I'm gonna go ahead and also add a link to your version for people using swift.

Cheers!

**Comment by krispenney** [comment]
Thanks @nimati, I just merged my project back to master and got rid of my swift branch, so you may want to update your link if you originally linked to the swift branch.

**Comment by nimati** [comment]
@k9101 just updated it, if you want you can also add this to your README for ease of use:

```
#Objective C

For the Objective C version of FCAlertView, [click here](https://github.com/nimati/FCAlertView).
```

At the very top before installation

**Comment by krispenney** [comment]
@nimati for sure, I added that in.
