### ISSUE TITLE
It's almost same with SCLAlertView

### ISSUE THREAD

**Issue by ismaiI1** [nimati/FCAlertView#14]
Did you edit @dogo's [https://github.com/dogo/SCLAlertView](url) ? I think you add to bottom 
Inspired By SCLAlertView

**Comment by nimati** [comment]
Hey @invisible66,

I'm aware of SCLAlertView as I've used it in a few projects. However, FCAlertView wasn't inspired or edited from it. It's actually been completely designed from scratch for our app at [ShiftRide](http://www.shiftride.com), you can see the original mockups (done in Sketch) here:
<br>
<img width="427" alt="mockup" src="https://cloud.githubusercontent.com/assets/7935593/18239300/59ac8106-7312-11e6-994b-d02cf4c40ebd.png">

Cheers!

**Comment by ismaiI1** [comment]
Ok, i got it 👍 :). and FCAlertView looks great.

**Comment by nimati** [comment]
Cheers! 😀
