### ISSUE TITLE
button title color 

### ISSUE THREAD

**Issue by guanzhendong** [nimati/FCAlertView#19]
want to add a property to custom button title color

**Comment by nimati** [comment]
I was gonna do a custom background color as well for this actually, so I'll consider adding both background and title color for custom buttons soon. Thanks for sharing!

**Comment by nimati** [comment]
Hi @guanzhendong 

Just pushed a new release V1.1.2 includes a bunch of new customizations you might enjoy. I haven't forgotten about custom buttons yet, that's the next step and will be released shortly! 

Thanks for using FCAlertView 👍

**Comment by guanzhendong** [comment]
@nimati haha,thank you

**Comment by nimati** [comment]
Hi @guanzhendong 

Please use the latest release V1.2.0, which includes customization for the button's title color and even background color 👍 Here's the sample code:

``` Objective-C
alert.firstButtonTitleColor = [UIColor blueColor];
alert.firstButtonBackgroundColor = [UIColor whiteColor];
```
