### ISSUE TITLE
Your demo have a bug

### ISSUE THREAD

**Issue by Coderii** [nimati/FCAlertView#2]
I have found your demo has a little bug which maybe not important.when I turn 'Outside Touch' Off and turn 'Hide Done Button' On at the same time，your alertView which showed can't close.

**Comment by nimati** [comment]
Thanks for catching that! This was one of the things I was thinking on how to approach fixing. Best thing that came to mind is to create a safety mechanism such that incase user is locked out of closing the alert (like when you hide the buttons), it will automatically force 'Outside Touch' to be On. Note that it might not show in the Example app that it's on, but if you try it out, it will be on in the background. Check out the latest commit, cheers!
