### ISSUE TITLE
Fixed width

### ISSUE THREAD

**Issue by guanzhendong** [nimati/FCAlertView#20]
now FCAlertView has fixed margin and fixed height  
        defaultSpacing = 105.0f;
        defaultHeight = 200.0f; 
i want to fix the width and height , can you provide two properties ?

**Comment by nimati** [comment]
I'll look into it for sure. Thanks!

**Comment by nimati** [comment]
Hi @guanzhendong 

You can use the latest commit to do what you desired, however please be cautious with changing these values, currently it's been optimized to look best on all iPhone sizes:

``` Objective-C
alert.customHeight = X;
alert.customSpacing = Y;
```

Cheers 💯

**Comment by nimati** [comment]
Note: this will be included in the next Pod release (in the upcoming days)

**Comment by guanzhendong** [comment]
@nimati   haha, thank you

**Comment by nimati** [comment]
No problem @guanzhendong Enjoy!
