### ISSUE TITLE
I can't change button tint and background colour.

### ISSUE THREAD

**Issue by moneyfreeuse** [nimati/FCAlertView#22]
The following properties I can't set. Please help me. Thanks.

alert.firstButtonTitleColor = [UIColor blueColor];
alert.secondButtonTitleColor = [UIColor blueColor];

alert.firstButtonBackgroundColor = [UIColor whiteColor];
alert.secondButtonBackgroundColor = [UIColor blackColor];

**Comment by nimati** [comment]
Hi @moneyfreeuse 

Are you using Cocoapods?

**Comment by nimati** [comment]
Hi @moneyfreeuse 

You should be able to update to the latest release and change the button background and title color. Please let me know if there are any further issues.

Cheers 👍
