### ISSUE TITLE
Long message

### ISSUE THREAD

**Issue by hacky12** [nimati/FCAlertView#24]
Hello,

I should be setup the long message, but the message appeared very small size

Please help this

Please refer to attached image
Best Regards,
![img_1084](https://cloud.githubusercontent.com/assets/3422920/19759004/db542f70-9c65-11e6-998c-36c2ce92e5c9.PNG)

**Comment by nimati** [comment]
Hi @hacky12 ,

Thank you for mentioning this, I will create an update in the coming days to fix this issue and 
make the alert stretch more vertically.

Cheers,
Nima

**Comment by nimati** [comment]
Hi there,

Please use the latest release, V1.2.0 for a fix for this issue. 
Let me know if it works better now. Don't forget to run `pod update` if you're using Cocoapods.

Thanks for using FCAlertView

**Comment by hacky12** [comment]
Awesome! 

Thank you so much!

**Comment by nimati** [comment]
No problem at all!

**Comment by mradzinski** [comment]
Hey @nimati, I'm having an issue similar to this where a long message gets truncated regardless of the height of the alert view. Is there a way to make the label fit the message without truncating it?

<img width="231" alt="captura de pantalla 2016-12-10 a las 12 12 14" src="https://cloud.githubusercontent.com/assets/4214209/21074214/22ff61ee-bed2-11e6-94d7-362b4250dd5c.png">


I'm using the latest version of the pod. I do believe that by setting the subtitle label to match the container height should solve this, but no idea if there's some other solution.

**Comment by mradzinski** [comment]
@nimati Just saw you are limiting the max number of lines to 6

https://github.com/nimati/FCAlertView/blob/master/FCAlertView/Classes/FCAlertView.m#L357

Any reason for this or is just because it was not expected to have a long message? I do believe that if it's possible to control the height of the alert view via customHeight property then the maximum amount of lines shouldn't be a concern (If the user exceeds the height then it should set a custom height)

**Comment by nimati** [comment]
Hi @mradzinski 

This is actually a big issue, originally FCAlertView was created to present a maximum of 6 lines, however, as I've got to use it in my own apps and see other people use it, I've seen that 6 lines is not that much. So what I've done is that I've removed the number of lines restrictions and instead adjust the frame of the descriptionLabel to match your text. Please try it out using V1.2.8 (now released) and let me know if it's good.

Cheers! 
Thanks for using FCAlertView 👍
