### ISSUE TITLE
Can't create heart rating view in swift

### ISSUE THREAD

**Issue by O-mkar** [nimati/FCAlertView#25]
i was unable to create alert.makeAlertTypeRateHearts()

Value of type 'FCAlertView' has no member 'makeAlertTypeRateHearts'

**Comment by nimati** [comment]
Hey @O-mkar 

Unfortunately right now, features after V1.0.0 aren't available in Swift.
I'll be working on implementing it in the coming days and will let you know
once it's ready.

Cheers,
Nima
