### ISSUE TITLE
Feature: Custom image scale?

### ISSUE THREAD

**Issue by dilizarov** [nimati/FCAlertView#28]
I actually sort of have this in my fork already, but I think this library is pretty great and can be expanded even further. One small thing would be for someone to define the scale of the image within the white background.

Some images just look better if they were a bit bigger.

for instance, by default we have:

```
alertViewVector.frame = CGRectMake(alertViewContents.frame.size.width/2 - 15.0f,
                                           -15.0f,
                                           30.0f,
                                           30.0f);
```

We could maybe do something like:

```

size = 30.0f * scale;

alertViewVector.frame = CGRectMake(alertViewContents.frame.size.width/2 - size/2,
                                           -size/2,
                                           size,
                                           size);
```

The scale would ideally be a number that defaults to 1 and goes up to 2, because at 2 it is the size of the entire circle.

Just an idea to think about. I write in Swift pretty exclusively, so the above might be sloppy/invalid Objective-C lol, but you get the point.

**Comment by nimati** [comment]
Hi there, 

Thank you for suggesting this, I can see how it could be useful for some developers. 
I've implemented your method in FCAlertView V1.2.6. You can update and enjoy the release. Here's how it works:

``` Objective-C
alert.customImageScale = 1.5; // or set 1.5 to desired range of scale between 0 and 2
```

Thanks for using FCAlertView! Also, if you'd like to contribute and update the Swift version of FCAlertView, please let me know. 

Cheers,
Nima
