### ISSUE TITLE
FCAlertView Warning: Your Alert should have a title and/or subtitle.

### ISSUE THREAD

**Issue by pjebs** [nimati/FCAlertView#29]
I have a `subtitle` but no `title`.
It logs: `FCAlertView Warning: Your Alert should have a title and/or subtitle.` incorrectly.

**Comment by nimati** [comment]
Great catch @pjebs!
It was due to an unnecessary check of customizations before they were set. I've fixed this in [Release 1.2.7](https://github.com/nimati/FCAlertView/releases/tag/1.2.7)

Cheers 👍
