### ISSUE TITLE
Block version

### ISSUE THREAD

**Issue by pjebs** [nimati/FCAlertView#3]
Can you make a block version so when you press a button, a block is fired?

**Comment by nimati** [comment]
Hi pjebs,

That should be doable, I'm gonna look into it soon!
Just to make sure we're on the same page, you're referring to something like this, correct?

```
[alert addButton:@"Button" actionBlock:^(void) {
   // Action for Button
}];
```

**Comment by pjebs** [comment]
Yes. See also: https://github.com/ryanmaxwell/RMUniversalAlert

**Comment by nimati** [comment]
Cool, just put the action block together. 
Try it out with the latest commit and let me know if it's good.

``` Objective-C
[alert addButton:@"Block Button" withActionBlock:^{
    NSLog(@"Block Button Clicked");
    // Put your action here
}];
```

**Comment by pjebs** [comment]
How can we put block for "Done" button. Other than that looks good.

**Comment by pjebs** [comment]
I would still prefer the style similar to how the blocks work for RMUniversalAlert however.

**Comment by nimati** [comment]
Hey, just added it:

``` Objective-C
[alert doneActionBlock:^{ 
    // Put your action here
}];
```

I'll check out RMUniversalAlert and maybe implement how they do it in the future. 
Let me know if it's all good for now.

Cheers!
