### ISSUE TITLE
Adding of custom view to alert

### ISSUE THREAD

**Issue by iamluckykim** [nimati/FCAlertView#30]
Hi!

First of all, thank you for that great library.
Please, tell me, how can I add custom view to alert such as UIProgressView and others?

When I adding my custom view as a subview to FCAlertView object it's added to alertBackground, but I want to add it to alert, below title and above buttons. How can I make this?

Thank you.

**Comment by nimati** [comment]
Hi @iamluckykim 

Thank you so much for using FCAlertView.
At this point, adding extra UIView to the FCAlertView would not be supported and/or recommended. 
This is to keep the alert simple and within the base guidelines. As an example, framing of different items could become an issue the more you could add to it. If anything changes in the future, however, I will let you know. 

Thanks again!
