### ISSUE TITLE
Can't Add Multiple UITextFields

### ISSUE THREAD

**Issue by CivicFan** [nimati/FCAlertView#32]
Hi,
first of all thank you for this great job.
Coming to the issue, I can't understand why from outside the library seems like multiple textfield are managed, but inside the code this is not done. Is it something that you're going to manage?

Davide

**Comment by nimati** [comment]
Hi there,
Thank you for using FCAlertView! Great issue you brought up. The answer is yes... textfields was one of the features I implemented for easy access to 1 fields for most use cases, however, in the future I'm planning to allow multiple textfields to be added. (maybe up to 2-3 fields at most). I will keep the issue open and keep you posted when this is ready. Cheers! 👍

**Comment by nimati** [comment]
Sorry for the delay, this feature is now in development!

**Comment by nimati** [comment]
@CivicFan 

This feature has been added to FCAlertView V1.4.0. Please update and try it by adding multiple ones like such: Thanks for using FCAlertView!

```Objective-C
        [alert addTextFieldWithPlaceholder:@"Email Address" andTextReturnBlock:^(NSString *text) {
            NSLog(@"TextField Returns: %@", text); // Do what you'd like with the text returned from the field
            
        }];
        
        [alert addTextFieldWithPlaceholder:@"First Name" andTextReturnBlock:^(NSString *text) {
            NSLog(@"TextField Returns: %@", text); // Do what you'd like with the text returned from the field
            
        }];
```
