### ISSUE TITLE
Delegate not working in Swift

### ISSUE THREAD

**Issue by mradzinski** [nimati/FCAlertView#34]
For some reason, it seems that the FCAlertViewDelegate causes issues in Swift. Although FCAlertView class is imported and recognized, as soon as I try implementing the delegate (or inherit from it) Swift reports that the class FCAlertView is not defined anymore, which makes little sense because FCAlertViewDelegate (which is part of the same class) is properly recognized.

<img width="748" alt="captura de pantalla 2016-12-10 a las 15 24 22" src="https://cloud.githubusercontent.com/assets/4214209/21075296/c4af573c-beec-11e6-8680-29ae7f5ec985.png">

I do have FCAlertView.h in my bridging header file, so that's not the issue, and sadly I cannot use the Swift version of this pod because we are still stuck with Swift 2.2 and our guidelines forbid the use of libraries which are not part of CocoaPods

**Comment by nimati** [comment]
Hi @mradzinski 

Intersting, I'll look into it, just wondering, are you using the [Swift version of FCAlertView](https://github.com/k9101/FCAlertView)?

**Comment by mradzinski** [comment]
@nimati Not really, I'm not sure if the Swift version supports Swift 2.2 (yes, we are still stuck with it). Also, we have strict guidelines regarding libraries which are not part of CocoaPods or have no pod-way to install. The Swift version still lacks pod support, so I'm not able to use it.

**Comment by nimati** [comment]
@mradzinski interesting, the Swift version was contributed by one of FCAlertView's users actually, we're working together to hopefully improve the Swift version in the near future. So right now you're using the Objective-C written version to generate your alert? And the issue is with the delegate functions?

**Comment by mradzinski** [comment]
Yes @nimati, I'm using the Obj-c version and the issue happens every time I try implementing the FCAlertViewDelegate protocol. If I delete the protocol from my class FCAlertView gets instantly recognized as a valid class, but if I implement FCAlertViewDelegate then FCAlertView fails to be recognized.

**Comment by nimati** [comment]
Interesting, I'm gonna look into it. In the meantime please send me the screenshot from all the code involved including the bridging header so I can recreate the situation. Cheers! 👍
