### ISSUE TITLE
Dark theme with textfield textcolor = white

### ISSUE THREAD

**Issue by rjpalermo1** [nimati/FCAlertView#35]
Hi - just stumbled upon this and running it through some tests and so far love it!  Very good job.

I'm not a good dev can get by - but not good enough to pull, figure out and fix.  So if you don't mind I'll just make some suggestion here as I go along and see if they make sense to you.

I like your dark theme - good thinking there.  I'm trying a textfield in it and the text is black so it is hard to see in a dark text field.

**Comment by nimati** [comment]
@rjpalermo1 

Good catch! I will fix this ASAP and let you know once it's fixed.

**Comment by nimati** [comment]
Hi @rjpalermo1,

Thanks again for bringing this to my attention. I've added a fix for this in V1.2.9. Cheers 👍
