### ISSUE TITLE
Set background Opacity

### ISSUE THREAD

**Issue by rjpalermo1** [nimati/FCAlertView#36]
How about a setting to control the background opacity?   Maybe also background color but I'd like to make the background a bit darker.

**Comment by nimati** [comment]
Hi @rjpalermo1 

Thank you for the suggestion! I'm not fully sure if the opacity is the best idea for a customization (complication of the whole design might occur) but I will look into changing background color to a custom one and let you know.

**Comment by nimati** [comment]
Hi @rjpalermo1 

I've added a feature to set a custom background color for the FCAlertView in V1.2.9. Please try it out and let me know if everything's working. Here is the code to apply the change:
just the background color setting:
```Objective-C
alert.alertBackgroundColor = [UIColor blueColor];
```
Or with opacity changes:
```Objective-C
alert. alert.alertBackgroundColor =  [UIColor colorWithWhite:200.0f/255.0f alpha:0.8];
```

Cheers 👍

**Comment by rjpalermo1** [comment]
Thank you - I'll update tomorrow and let you know if I run into any
problems!

One quick question - I can add buttons, delegate and run my methods to
added buttons no problem.

If I add only a single button and the DONE button both buttons are side by
side.
If I add 2 buttons and the DONE button = nil, the 2 buttons I add are side
by side
If I add a DONE button, add 2 buttons and alert.hideButton = YES the 2
buttons are side by side
If I add a DONE button, add 2 buttons and alert.hideButton = NO the 3
buttons stacked full width

How can I get a DONE button and only 1 other button to stack full width?
Is it possible?

**Comment by nimati** [comment]
@rjpalermo1 

No worries, sure thing!
And that's an interesting one, right now only 3 buttons would stack full width. 

Cheers!
