### ISSUE TITLE
Not working dismiss

### ISSUE THREAD

**Issue by GameDevMex** [nimati/FCAlertView#37]
Whenever I dismiss the FCAlertView, it never appears again.

**Comment by nimati** [comment]
@GameDevMex 
Hi there, 
Can I see the code and the methods you're using to present and dismiss the alert with?

**Comment by nimati** [comment]
@GameDevMex Hey there, are you possibly using any animations? If you let me know all the customizations you're using and the code, I might be able to help. Cheers 👍
