### ISSUE TITLE
Simulator issue

### ISSUE THREAD

**Issue by shoaibhussan** [nimati/FCAlertView#39]
I am unable to run this code on Simulator and it worked on device,
please tell me what should i change in it for Simulator.
<img width="926" alt="screen shot 2017-01-04 at 4 00 16 pm" src="https://cloud.githubusercontent.com/assets/2375979/21640381/062b9fdc-d297-11e6-99c8-a46ed1c0e592.png">

**Comment by nimati** [comment]
Hi Shoaib,

Thank you for using FCAlertView. Hmm.. that's strange. Could you please copy and paste the code you're using to present the alert? I can try to go through it and see if the problem is with that or your Xcode/device. I've tried using the Simulator and it works fine on my end. 

Cheers! 👍
