### ISSUE TITLE
Simple modification 

### ISSUE THREAD

**Issue by ZKRed01** [nimati/FCAlertView#4]
Hi, 
this is not a issue only a simple comment.
If someone want to use (custom) image without tint color simply change buttonWithType: from UIButtonTypeSystem to UIButtonTypeCustom 
See code: **FCAlertView.m**
line 463:
UIButton *alertViewVector = [UIButton buttonWithType:UIButtonTypeCustom];
    alertViewVector.frame = CGRectMake(alertViewContents.frame.size.width/2 - 15.0f,
                                       -15.0f,
                                       30.0f,
                                       30.0f);
    [alertViewVector setImage:vectorImage forState:UIControlStateNormal];
    alertViewVector.userInteractionEnabled = 0;
    //alertViewVector.tintColor = _colorScheme;

Thank you, good job!

**Comment by nimati** [comment]
Hey there,

You brought up a good point. I'm gonna go ahead and add a fix for this in the next commit. Will keep you posted on it.

Cheers!

**Comment by nimati** [comment]
Hi, 

Just added this to the latest commit, please try it out by simply adding the following line and let me know how it goes! Thanks again for bringing it up!

``` Objective-C
alert.avoidCustomImageTint = 1;
```
