### ISSUE TITLE
BounceAnimations = False --> Dismissed event not called

### ISSUE THREAD

**Issue by Jan-M-B** [nimati/FCAlertView#40]
Hi,

when BounceAnimations is set to False and you use In and Out Animations, the Dismissed event is not called.

Jan

**Comment by nimati** [comment]
Hi @Jan-M-B,

Thank you for using FCAlertView and thanks for bringing this to my attention. This is now fixed in V1.2.9. Please try it out and let me know if everything's working. Cheers 👍
