### ISSUE TITLE
Changing textfield properties

### ISSUE THREAD

**Issue by FouadRaheb** [nimati/FCAlertView#41]
It would be useful to be able to set a default value for the textfield as well as changing other properties.

My Current workaround is updating the properties after a delay.

        DISPATCH_AFTER(0.2, {
                alert.textField.autocapitalizationType = UITextAutocapitalizationTypeNone;
                alert.textField.text = text;
        });

**Comment by nimati** [comment]
Huh interesting workaround. Thanks for bringing this up @FouadRaheb, will look into adding this into the next release.

**Comment by nimati** [comment]
This is now under dev. Sorry for the wait.

**Comment by nimati** [comment]
@FouadRaheb 

This feature has been added to FCAlertView V1.4.0. Please update and try it by replacing your TextField alert using this:

```Objective-C
UITextField *customField = [[UITextField alloc] init];
customField.autocapitalizationType = UITextAutocapitalizationTypeAllCharacters;
        
[alert addTextFieldWithCustomTextField:customField andPlaceholder:@"Placeholder" andTextReturnBlock:^(NSString *text) {
     NSLog(@"Custom TextField Returns: %@", text); // Do what you'd like with the text returned from the field
}];
```

Thanks for using FCAlertView!
