### ISSUE TITLE
Alert not showing

### ISSUE THREAD

**Issue by Mar-k** [nimati/FCAlertView#42]
I am using the latest pod version of FCAlertView

The alert view is not showing for me, the first few times.

This is the code I use to show the FCAlertView (Method 1):
`let alert = FCAlertView()
        alert.makeAlertTypeWarning()
        alert.blurBackground = true
        alert.showAlert(withTitle: nil, withSubtitle: withText.localized, withCustomImage: nil, withDoneButtonTitle: nil, andButtons: nil)`

Or this way (Method 2):

`let alert = FCAlertView()
                alert.colorScheme = "#8DCA63".hexColor
                alert.blurBackground = true
                alert.dismissOnOutsideTouch = true
                alert.avoidCustomImageTint = true
                alert.delegate = self
alert.showAlert(withTitle: nil, withSubtitle: "String", withCustomImage: UIImage(named: "image") , withDoneButtonTitle: "String", andButtons: ["String"])
`

But it only shows when I call it the way I showed above in a certain view controller.

Let's say we have VC1, VC2 and VC3

I call the Method 2 in VC1 and it doesn't show an alert, then I call the Method 1 in VC2 and it doesn't show an alert, then in VC3 I call Method 2 and it shows an alert. After it shows up the first time it shows up on every VC.

Maybe I am doing something stupid or wrong, but I've tried everything and I can't get it to work...

I hope someone haves a solution

**Comment by Mar-k** [comment]
@nimati

**Comment by Mar-k** [comment]
I made such a stupid mistake. Sorry for the hassle. I was calling the second method from a seperate class and not directly on a viewcontroller. Then I noticed that there was also this method:

`alert.showAlert(inView: <#T##UIViewController!#>, withTitle: <#T##String!#>, withSubtitle: <#T##String!#>, withCustomImage: <#T##UIImage!#>, withDoneButtonTitle: <#T##String!#>, andButtons: <#T##[Any]!#>)`

So I passed the view and it worked. Again sorry :)

**Comment by nimati** [comment]
@Mar-k No worries, and no hassle at all! Glad you got it solved :)
