### ISSUE TITLE
Change Font of Title and SubTitle

### ISSUE THREAD

**Issue by tilakjethva** [nimati/FCAlertView#45]
Hello, I am not found titleFont and subtitleFont properties of alert. How can I change font of Title and Subtitle?

**Comment by nimati** [comment]
Hi there, are you using the latest version of FCAlertView? [V1.3.1](https://github.com/nimati/FCAlertView/releases/tag/1.3.1)

**Comment by tilakjethva** [comment]
Ohhh Sorry, @nimati  I have used old version. Now, I have updated it pod 'FCAlertView', '~> 1.3' works fine.
Thank you so much. 👍
