### ISSUE TITLE
TextField & multiple buttons

### ISSUE THREAD

**Issue by CKzu** [nimati/FCAlertView#46]
Hi and first of all thanks for the great job!

I have a small issue with textfields on my alert view.

Basically what I'm displaying is an alert view with a text field and two buttons : `OK` and `Cancel`.
My issue here is that the return block in `alert.addTextField(withPlaceholder:_, andTextReturn:_)` doesn't tell me which button was pressed, and the delegate seems to be called before the return block, so I can't store the content of the text field in a variable.

Is there any workaround for this?

Thanks!

**Comment by nimati** [comment]
Hi @CKzu Thank you! I'm aware there's an issue there, I'll look into it and let you know.

**Comment by nimati** [comment]
Hi @CKzu 

The delegate has been changed to return text field before the button press now. Please try the new FCAlertView Release V1.4.0. and let me know if there's still an issue with this.

Thanks for using FCAlertView!
