### ISSUE TITLE
Blurry Background

### ISSUE THREAD

**Issue by pjebs** [nimati/FCAlertView#5]
It would be nice if you can add blurry background using 
`https://github.com/ivoleko/ILTranslucentView` for iOS 7 and `UIVisualEffectView` for iOS 8+.

The ILTranslucentView repo has objc and swift code. Unfortunately you won't be add it as a cocoapod dependency since ios7+swift+cocoapods doesn't mix and the guy put the objc files and swift files in same folder so cocoapods gets confused if you try and use only the obj files: https://github.com/ivoleko/ILTranslucentView/issues/20

@https://github.com/nimati/FCAlertView/blob/master/FCAlertView/Classes/FCAlertView.m#L36:

You can do an objective-C version of below code. (I use swift for my project)

```
        if #available(iOS 8.0, *) {
            // Use UIVisualEffectView
            let tvev = UIVisualEffectView(effect:  UIBlurEffect(style: .Dark))
            tvev.translatesAutoresizingMaskIntoConstraints = false
            _alertBackground.addSubview(tvev)
        } else {
            //For iOS 7 - Use ILTranslucentView
            (self.viewExternal as! ILTranslucentView).translucentAlpha = 1
            (self.viewExternal as! ILTranslucentView).translucentStyle = .Black
            (self.viewExternal as! ILTranslucentView).translucentTintColor = UIColor.clearColor()
            self.viewExternal.backgroundColor = UIColor.clearColor()
        }
```

**Comment by nimati** [comment]
Hey @pjebs ,

Thanks for pointing this out as well! This is something I'm looking to do some testing on and release in the next release. Keep me posted if you find any other resources that would be helpful.

Cheers

**Comment by pjebs** [comment]
I've used that library for a while. works well.

**Comment by nimati** [comment]
Nice, I'll take a look soon.

**Comment by nimati** [comment]
@pjebs Currently working on this. Will have a release soon for you to test.

**Comment by pjebs** [comment]
Remember to do your iOS 8 check like this:

```
if (NSClassFromString(@"UIVisualEffectView") != nil) {
 //iOS 8+
} else {
//iOS 7
}
```

rather than `[UIVisualEffectView class]`

**Comment by nimati** [comment]
Nice, will add the check.

**Comment by nimati** [comment]
Not yet ready for release, but if you download the repo with latest commit, you should be able to use the following, you can create the blur background effect. Let me know how it looks and how you feel about it. Once it's finalized, will add it to cocoapods. @pjebs 

``` Objective-C
alert.blurBackground = YES;
```

**Comment by nimati** [comment]
Use 271f0a5

**Comment by pjebs** [comment]
As the code currently is, it won't be iOS 7 compatible which some people require (inc myself).
The `ILTranslucentView` library is MIT licensed so you can add it with your repo. That would make it complete.

**Comment by nimati** [comment]
I see, I'll take a look at ILTranslucentView, what's your thought on the blur itself?
