### ISSUE TITLE
FCAlertView close on touch outside when should not.

### ISSUE THREAD

**Issue by andres9394** [nimati/FCAlertView#50]
Hi, this is my code but first a short explanation:
The alert view dismiss on outside touch no matter if I setting "NO" and I need the alert view to dismiss just when the background task have done! I guess this is a mistake in the alertView because the alert view dismiss when should not. Sorry for the english, I hope you can fix it, thank you and have a nice day.
 
`[alert setDismissOnOutsideTouch:NO];
  [alert showAlertWithTitle:@"Sending, please wait..." withSubtitle:nil withCustomImage:nil withDoneButtonTitle:nil andButtons:nil];
 dispatch_queue_t queue = dispatch_queue_create("My queue", NULL);
 dispatch_async(queue, ^{
         //code to be executed in the background
         NSLog(@"Inside background task");
         [self sendDataToServer:@"POST"];
         dispatch_async(dispatch_get_main_queue(), ^{
         //code to be executed on the main thread when background task is finished
         NSLog(@"task done");
         [alert dismissAlertView];
});
`

**Comment by nimati** [comment]
Hi @andres9394 

Thank you for using FCAlertView. I ran your code through my example app and it seems to be working fine. Is the issue that when the user touches OUTSIDE of the alert box, it dismisses? Would like it not dismiss at all even I press the buttons? Also, if you are adding any other customizations to the FCAlertView, please paste the code here so I can take a closer look.

**Comment by goodstechinc** [comment]
Has this issue been resolved?

**Comment by andres9394** [comment]
Sorry. No, this issue has not been resolved. What I want is that when I touched outside of the alert box, it no not dismisses. The alert box should dismiss only if I touch the cancel button.

**Comment by nimati** [comment]
@andres9394 I took a second look at your code, I think what's happening is that there's no button in your alert and there is no timer set to dismiss it. This automatically triggers ```[alert setDismissOnOutsideTouch:YES];``` However, in the next version, you'll be able to bypass it.

**Comment by nimati** [comment]
This has been added to FCAlertView V1.4.0. Please try adding this to override the forced close:

```Objective-C
alert.overrideForcedDismiss = 1;
```

Thanks for using FCAlertView!
