### ISSUE TITLE
Can we add multiple textfield with FCAlertview ???

### ISSUE THREAD

**Issue by ruchiteasternts17Dec** [nimati/FCAlertView#51]

**Comment by nimati** [comment]
Sorry for the delay, this feature is now in development!

**Comment by bayfatih2000** [comment]
I am waiting it. Please add it.
Thanks

**Comment by nimati** [comment]
Hi @bayfatih2000 This feature will be released in the next update (within the next week) Thanks for your patience!

**Comment by nimati** [comment]
Yes! You finally can add multiple textfields. This feature has been added to FCAlertView V1.4.0. Please update and try it by adding multiple ones like such:

```Objective-C
        [alert addTextFieldWithPlaceholder:@"Email Address" andTextReturnBlock:^(NSString *text) {
            NSLog(@"TextField Returns: %@", text); // Do what you'd like with the text returned from the field
            
        }];
        
        [alert addTextFieldWithPlaceholder:@"First Name" andTextReturnBlock:^(NSString *text) {
            NSLog(@"TextField Returns: %@", text); // Do what you'd like with the text returned from the field
            
        }];
```

Thanks for using FCAlertView!

**Comment by marcelosantoro** [comment]
How can i do it in Swift ??? Can you show me syntax ?

**Comment by nimati** [comment]
Try this: (you can add up to 4 fields max)

```Swift
alert.addTextField(withPlaceholder: "Placeholder") { (text) in
     print(text!)
}
     
alert.addTextField(withPlaceholder: "Placeholder") { (text) in
     print(text!)
}
```

**Comment by marcelosantoro** [comment]
@nimati Perfect man... it worked ... awesome !!! Thank you very much !!!

**Comment by nimati** [comment]
No problem!! Thanks for using FCAlertView 👍 😃 @marcelosantoro

**Comment by cdeck95** [comment]
How can you do this (in swift) but get the text from *all* text fields when the done button is clicked? I am trying to implement `FCAlertDoneButtonClicked(alertView: FCAlertView)` but I am unsure how to get the text field values.
