### ISSUE TITLE
Title on two lines

### ISSUE THREAD

**Issue by ipefixe** [nimati/FCAlertView#52]
Hi,

This is a proposal to improve this succulent framework!

It would be nice that we can have a title on two lines when it's needed. In my natural language, some words are long, and on iPhone, it's very fast to have something like:

> "Réinitialiser votre code..."

Instead of:

> "Réinitialiser votre code PIN"

Thank you!

**Comment by Th3nion** [comment]
Hello,
I have the same problem, titles too long are truncated with "..."
Do you have found any trick to resolve it ?

Thanks

**Comment by nimati** [comment]
Hi there, thanks for bringing this to my attention. I will look into adding a way for 2 line titles in the next update. Cheers!

**Comment by nimati** [comment]
Hi there,

This has now been fixed in V1.4.0. Try it and let me know if it's good.

Thanks for using FCAlertView! 😄
