### ISSUE TITLE
Detect interface orientation NOT device orientation

### ISSUE THREAD

**Issue by cateatercode** [nimati/FCAlertView#53]
Thank you for creating this nice control.

Please change device orientation to interface orientation to reflect the current app orientation and not the device. The device may lay down flat on a table but the interface orientation will always be either landscape or portrait.

Thanks.

Line 337 
change
if (UIDeviceOrientationIsLandscape([UIDevice currentDevice].orientation))
to
if(UIInterfaceOrientationIsLandscape([UIApplication sharedApplication].statusBarOrientation))

**Comment by nimati** [comment]
Hi there,

Thanks for pointing this out. This has now been fixed in V1.4.0. Try it and let me know if it's good.

Thanks for using FCAlertView 😄
