### ISSUE TITLE
Use keyWindows instead of windows.lastObject

### ISSUE THREAD

**Issue by cateatercode** [nimati/FCAlertView#54]
The last object may not be visible on the screen. I.e. keyboard controls. Its better to use the keyWindow here.

Line 1174
Use
UIWindow* window = [[UIApplication sharedApplication] keyWindow];
instead of
UIWindow *window = [UIApplication sharedApplication].windows.lastObject;

**Comment by nimati** [comment]
Thanks again for pointing this out too. This has now been fixed in V1.4.0. Try it and let me know if it's good.

Thanks for using FCAlertView 😄
