### ISSUE TITLE
How to change button bg color on press?

### ISSUE THREAD

**Issue by hsklia** [nimati/FCAlertView#55]
How to change button background color for press state?

**Comment by nimati** [comment]
Hi there,

This feature has been added to FCAlertView V1.4.0. Try it by adding these as desired to your buttons:

```Objective-C
alert.doneButtonHighlightedBackgroundColor = [UIColor redColor];
alert.firstButtonHighlightedBackgroundColor = [UIColor redColor];
alert.secondButtonHighlightedBackgroundColor = [UIColor redColor];
```

Thanks for using FCAlertView 😄
