### ISSUE TITLE
Alert type progress with completion block

### ISSUE THREAD

**Issue by chienplee** [nimati/FCAlertView#57]
Hi, 
Thanks for the great library. Just one question:

With the alert type set to progress, can we have a completion block included with this type?
What I want to do is when a button is clicked, display the alertview with type progress telling user that I am connecting to a database, after getting response from database, the alert view hides or make alert type success, but I don't want to display button to users. 

PS. If forced dismiss on outside touch can be disabled it will be ideal in my case.

![2017-05-26 14 18 30](https://cloud.githubusercontent.com/assets/16417906/26483178/4709bb82-421e-11e7-8983-5bc88e37c771.png)

**Comment by nimati** [comment]
Hi,
Thanks for using FCAlertView!

To make everything simple, here's what you could do in your situation. When you get a response from the database, dismiss the alert with the following line:

```Objective-C
[alert dismissAlertView];
```

And then you can present another alert at the same time that is of Success type, this is optional. But if you do decide to do this, you can also attach a timer to it to have it automatically go away.

In regards to forced close, I will add something to the next version of the alert to help you bypass the force close.

**Comment by chienplee** [comment]
Thanks.
