### ISSUE TITLE
Why  button can't set font

### ISSUE THREAD

**Issue by noname004** [nimati/FCAlertView#59]
how set button font?

**Comment by nimati** [comment]
This feature has been added to FCAlertView V1.4.0. Please update and try it by adding these as desired:

```Objective-C
alert.doneButtonCustomFont = [UIFont fontWithName:@"Avenir" size:20.0];
alert.firstButtonCustomFont = [UIFont fontWithName:@"Avenir" size:16.0];
alert.secondButtonCustomFont = [UIFont fontWithName:@"Avenir" size:16.0];
```

Thanks for using FCAlertView! 😄

**Comment by Ucdemir** [comment]
alert.doneButtonCustomFont works on ios 14
but not work on ios 12.4
