### ISSUE TITLE
maxWidth

### ISSUE THREAD

**Issue by pjebs** [nimati/FCAlertView#6]
For Portrait iPad, the box is really wide. It looks bad.

**Comment by nimati** [comment]
Hey, 

Thanks for pointing that out! Fully aware that the FCAlertView doesn't work well on iPad or in landscape mode either, as the first version was developed solely for iPhone portrait. These are both up for fixes that will be released soon, as mentioned on README.

Cheers! 👍

**Comment by nimati** [comment]
Hi @pjebs,

Check the UIFixes branch I just created, it adds a small fix for iPad portrait that should make it look normal now. Let me know if that works, I'm going to add more UI fixes on this branch including landscape, etc.

**Comment by pjebs** [comment]
Actually I checked out the branch using: `pod 'FCAlertView', :git => 'https://github.com/nimati/FCAlertView.git', :branch => 'UIFixes'` but it's not configured for cocoapods properly, so I couldn't test it it

**Comment by pjebs** [comment]
I tried it out manually - it works well. Cocoapods simply isn't configured properly.

**Comment by nimati** [comment]
Yep, the reason is I usually don't release small fixes as a new release, which is what Cocoapods requires as far as I'm aware. With that said, just released 1.0.7 as UIFixes. Enjoy!

**Comment by nimati** [comment]
Just wanted to point out that for this fix, use FCAlertView V1.0.7 or V1.0.9+
