### ISSUE TITLE
UI Freeze after SFSafariServices dismisses

### ISSUE THREAD

**Issue by ripventura** [nimati/FCAlertView#60]
Hi,
I may have found a pretty nasty bug.

How to reproduce:
1- Present a SFSafariServices with any URL
2- Dismiss de SFSafariServices modal by clicking "Done"
3- Hit a button that displays an alert

Expected result:
The alert should appear on screen

Current result:
The screen freezes and only accepts taps again after rotating the device to another orientation.

**Comment by nimati** [comment]
Hi there,

There was a small bug fix in V1.4.0. that may have solved this issue. Please try updating your FCAlertView and let me know if this issue still persists.

Cheers,
Nima

**Comment by ripventura** [comment]
Thanks @nimati!
I'll let you know if the issue persists after updating...

Regards,
Vitor Cesco

**Comment by nimati** [comment]
Sounds good, @ripventura 👍
