### ISSUE TITLE
Not showing on  beta versions.

### ISSUE THREAD

**Issue by irshadpc** [nimati/FCAlertView#61]
I tried to use this controller in beta devices and my experiences were very bad. Most of the time alert not showing in beta iOS versions some times it may not work in iOS 10.3 and later versions.

**Comment by nimati** [comment]
Hi @irshadpc 

Thanks for the heads up. Can you provide me more information and possibly screenshots or code snippets behind this? It'd be much appreciated.

Cheers,
Nima

**Comment by irshadpc** [comment]
@nimati I found a workaround for this.
`- (void) showAlertInView:(UIViewController *)view withTitle:(NSString *)title withSubtitle:(NSString *)subTitle withCustomImage:(UIImage *)image withDoneButtonTitle:(NSString *)done andButtons:(NSArray *)buttons {}`
Only the above method is working in iOS 10 beta and iOS 11 beta. If anything more please let me know.

**Comment by nimati** [comment]
@irshadpc That's interesting. Just so I can get a better idea of what might be going on, do you mind sending over the code you're using to generate the FCAlertView and in which method? (ViewWillLoad, ViewDidAppear, or after?) Thanks!

**Comment by cocoaniu** [comment]
iOS11:- (void)drawRect:(CGRect)rect does not perform @nimati

**Comment by cocoaniu** [comment]
Replace“     [window addSubview:self];
    [window bringSubviewToFront:self];” with“    [[[UIApplication sharedApplication].windows objectAtIndex:0] endEditing:YES];
    [[[UIApplication sharedApplication].windows objectAtIndex:0] addSubview:self];”
