### ISSUE TITLE
iOS11:- (void)drawRect:(CGRect)rect does not perform

### ISSUE THREAD

**Issue by cocoaniu** [nimati/FCAlertView#67]
iOS11:- (void)drawRect:(CGRect)rect does not perform，alertview can't show。

**Comment by cocoaniu** [comment]
Replace“     [window addSubview:self];
    [window bringSubviewToFront:self];” with“    [[[UIApplication sharedApplication].windows objectAtIndex:0] endEditing:YES];
    [[[UIApplication sharedApplication].windows objectAtIndex:0] addSubview:self];”

**Comment by fatenumber2** [comment]
Thank you very much!!
