### ISSUE TITLE
Hyperlink

### ISSUE THREAD

**Issue by VinothVKumar** [nimati/FCAlertView#79]
Is there any kind of feature for detecting hyperlinks inside the alertview. I just made a word inside the alert subtitle hyperlink using the attributed method but the touch event is not recognizing. If there is any solution, please reply ASAP.

**Comment by nimati** [comment]
Hi @VinothVKumar 

Please try using attributed strings to include links. FCAlertView allows you to use attributed string. Please refer to [this section of the readme](https://github.com/nimati/FCAlertView#extra-customizations). Here's an example:

`NSMutableAttributedString` * str = [[NSMutableAttributedString alloc] initWithString:@"Google"];
[str addAttribute: NSLinkAttributeName value: @"http://www.google.com" range: NSMakeRange(0, str.length)];

[alert showAlertWithAttributedSubTitle:str withAttributedSubtitle:str withCustomImage:_alertImage withDoneButtonTitle:nil `andButtons:self.arrayOfButtonTitles];`

Hope that helps!
