### ISSUE TITLE
nullability annotations 

### ISSUE THREAD

**Issue by pjebs** [nimati/FCAlertView#8]
`- (void)addButton:(NSString *)title withActionBlock:(FCActionBlock)action;
`\- (void)doneActionBlock:(FCActionBlock)action;`

Can you add nullability annotations to `action`. Either make it nullable (and handle the case  to prevent it getting put inside dictionary or make it `[NSNull null]`) or make it nonnull.

Currently this causes error in swift (as it would also in Obj-c):

`alert.addButton("OK".localized, withActionBlock: nil)`

**Comment by nimati** [comment]
Yep, fixed it in the latest release. Thanks!

**Comment by pjebs** [comment]
I noticed you removed annotations

**Comment by nimati** [comment]
Yeah, after putting the fix in place, I don't think it's necessary to keep it. You should still be able to pass nil to the withActionBlock and have it add the button, let me know if that works.
