### ISSUE TITLE
Support dark mode

### ISSUE THREAD

**Issue by sidan5** [nimati/FCAlertView#80]
Currently it does not support dark mode. Text could not be seen.

**Comment by sidan5** [comment]
Can be easily solved with that code:

```
if (@available(iOS 12.0, *)) {
    if (self.traitCollection.userInterfaceStyle == UIUserInterfaceStyleDark ) {
        [alert setDarkTheme:TRUE];
    }
}
```

**Comment by nimati** [comment]
@sidan5 Great workaround! I will look into properly implementing the iOS Dark Mode to enable Alert's Dark Mode by default.

**Comment by sidan5** [comment]
@nimati Cool. Thanks!
