### ISSUE TITLE
Error in index

### ISSUE THREAD

**Issue by geogerar** [nimati/FCAlertView#9]
Hi,
nice work indeed.
I would like to tell you that there is an error in "clickedButtonIndex:(NSInteger)index buttonTitle:(NSString *)title "
always index is 0 for anyone of the two additional buttons......
Can you please take a look and fix it?
Thank you very much

George

**Comment by nimati** [comment]
Hi,
Thank you @geogerar!
That's strange, I'll look into it and fix it as soon as possible.
Cheers!
Nima

**Comment by nimati** [comment]
Hi @geogerar,

Can I get the code you're using to generate the FCAlertView? Just so I can see exactly how you're adding the buttons and what you're getting as index. I just tested it using the Example App, I got back the following from 1 and 2 buttons:

``` Objective-C
2016-08-30 13:20:13.575 FCAlertView_Example[73293:919869] Button Clicked: 0 Title:First
2016-08-30 13:20:26.911 FCAlertView_Example[73293:919869] Button Clicked: 1 Title:Second
```
